/**
 * Midnight ZK Simulation Module
 *
 * Simulates the Midnight blockchain's zero-knowledge proof system.
 *
 * Architecture mirrors real Midnight:
 *   • "Compact contracts" are TypeScript classes with prove() / verify() methods
 *   • Document commitments are BLAKE2b-256 hashes (real Midnight uses Pedersen commitments)
 *   • Proof objects include simulated Groth16 transcript (π_A, π_B, π_C points)
 *   • Verification is a deterministic hash check (real Midnight uses bilinear pairings)
 *   • Circuit-specific verification keys are derived from known constants
 *
 * The security model:
 *   • Cannot forge a valid proof without knowing the document fields
 *   • Verification requires no access to the original document
 *   • Nullifiers prevent proof replay across different claims
 */

import {
    blake2b256,
    blake2b256str,
    toBase64,
    fromBase64,
    toHex,
    concat,
    randomSalt,
    randomId,
} from './crypto';
import {
    type SchemaType,
    renderClaimDescription,
} from './schemas';
import {
    MIDNIGHT_CONTRACT_PREFIX,
    MIDNIGHT_NETWORK_VERSION,
} from './config';

// ── Proof data types ─────────────────────────────────────────────────────────

/** Simulated Groth16 proof points (each point is a 32-byte hex string) */
export interface Groth16Proof {
    /** Simulated G1 point π_A */
    a:    string;
    /** Simulated G2 point π_B (two field elements) */
    b:    [string, string];
    /** Simulated G1 point π_C */
    c:    string;
}

/** A complete Midnight ZK proof bundle — safe to share publicly */
export interface MidnightProof {
    /** Unique proof identifier (hex) */
    proofId:           string;
    /** Schema type (document category) */
    schemaType:        SchemaType;
    /**
     * Deployed Compact contract ID.
     * In production: derived from the Contract address on Midnight blockchain.
     */
    contractId:        string;
    /** Claim type identifier */
    claimType:         string;
    /** Public claim parameters (revealed to verifier) */
    claimParams:       Record<string, unknown>;
    /** Human-readable description of what was proven */
    claimDescription:  string;
    /** The verdict — true means the claim holds */
    satisfiesClaim:    boolean;
    /**
     * BLAKE2b-256 commitment to (fields | owner | salt).
     * Irreversibly binds this proof to a specific document instance.
     */
    documentCommitment: string;
    /**
     * Nullifier: BLAKE2b(commitment | claimType | claimParams_json).
     * Prevents re-use of the same proof for different claims.
     */
    nullifier:         string;
    /** Simulated Groth16 proof transcript */
    proof:             Groth16Proof;
    /**
     * Verification hash: binds proof points to public inputs.
     * verificationHash = BLAKE2b(π_A | π_C | satisfiesClaim | nullifier | vk)
     */
    verificationHash:  string;
    /**
     * Circuit-specific verification key (derived from circuit constants).
     * In production: generated by Midnight trusted setup ceremony.
     */
    vk:                string;
    /** Wallet address of the proof generator */
    ownerAddress:      string;
    /** Unix timestamp (ms) */
    timestamp:         number;
    /** Optional expiry (Unix ms). Null = never expires. */
    expiresAt:         number | null;
    /** Simulated Midnight transaction hash */
    midnightTxHash:    string;
    /** Network version tag */
    networkVersion:    string;
}

/** Result returned by verifyProof */
export interface VerificationResult {
    valid:            boolean;
    satisfiesClaim:   boolean;
    claimDescription: string;
    schemaType:       SchemaType;
    claimType:        string;
    claimParams:      Record<string, unknown>;
    ownerAddress:     string;
    timestamp:        number;
    proofId:          string;
    contractId:       string;
    /** Human-readable summary for the verifier UI */
    summary:          string;
    error?:           string;
}

// ── Deployed contract registry ──────────────────────────────────────────────

/**
 * Simulated deployed Compact contract addresses organised by schema type.
 * In production: these are actual contract addresses on the Midnight chain.
 */
const DEPLOYED_CONTRACTS: Record<SchemaType, string> = {
    academic_credential: `${MIDNIGHT_CONTRACT_PREFIX}_aca_verify_v1`,
    income_statement:    `${MIDNIGHT_CONTRACT_PREFIX}_inc_verify_v1`,
    medical_record:      `${MIDNIGHT_CONTRACT_PREFIX}_med_verify_v1`,
    property_deed:       `${MIDNIGHT_CONTRACT_PREFIX}_prop_verify_v1`,
    identity_document:   `${MIDNIGHT_CONTRACT_PREFIX}_id_verify_v1`,
};

// ── Circuit verification keys ───────────────────────────────────────────────

/**
 * Derive the circuit verification key for a specific (schema, claim) pair.
 * In production: VKs come from the Midnight trusted setup ceremony for each Compact circuit.
 */
function deriveCircuitVK(schemaType: SchemaType, claimType: string): Uint8Array {
    // The VK is deterministically derived from the circuit's "constants" — the claim logic.
    // Any change to the circuit (schema + claim) produces a completely different VK,
    // just as in a real ZK circuit recompilation.
    return blake2b256str(
        `MIDNIGHT_GROTH16_VK:${schemaType}:${claimType}:circuit_constants_v1`
    );
}

// ── Claim evaluation (the "Compact circuit" logic) ──────────────────────────

/**
 * Evaluate whether a document's fields satisfy a claim.
 * This is the core of each Compact contract's prove() method.
 * Returns true (claim holds) or false (claim fails).
 */
export function evaluateClaim(
    schemaType:  SchemaType,
    fields:      Record<string, unknown>,
    claimType:   string,
    claimParams: Record<string, unknown>
): boolean {
    switch (schemaType) {
        case 'academic_credential':
            return evalAcademic(fields, claimType, claimParams);
        case 'income_statement':
            return evalIncome(fields, claimType, claimParams);
        case 'medical_record':
            return evalMedical(fields, claimType, claimParams);
        case 'property_deed':
            return evalProperty(fields, claimType, claimParams);
        case 'identity_document':
            return evalIdentity(fields, claimType, claimParams);
    }
}

function evalAcademic(
    fields: Record<string, unknown>,
    claimType: string,
    params: Record<string, unknown>
): boolean {
    const degreeType    = String(fields.degree_type    ?? '');
    const fieldOfStudy  = String(fields.field_of_study ?? '').toLowerCase();
    const accredited    = fields.accredited === true || fields.accredited === 'true';
    const gpa           = Number(fields.gpa ?? 0);

    const LEVELS = ['Associate', 'Bachelor', 'Master', 'PhD'];

    switch (claimType) {
        case 'has_degree_in': {
            const required = String(params.field ?? '').toLowerCase();
            return required.length > 0 && fieldOfStudy.includes(required);
        }
        case 'graduated_from_accredited':
            return accredited;
        case 'degree_level_at_least': {
            const minLevel = String(params.min_level ?? '');
            return LEVELS.indexOf(degreeType) >= LEVELS.indexOf(minLevel);
        }
        case 'gpa_above': {
            const threshold = Number(params.threshold ?? 0);
            return gpa > threshold;
        }
        default:
            return false;
    }
}

function evalIncome(
    fields: Record<string, unknown>,
    claimType: string,
    params: Record<string, unknown>
): boolean {
    const income         = Number(fields.annual_income  ?? 0);
    const employmentType = String(fields.employment_type ?? '');

    switch (claimType) {
        case 'income_above': {
            const threshold = Number(params.threshold ?? 0);
            return income > threshold;
        }
        case 'is_employed':
            return ['Full-time', 'Part-time', 'Self-employed', 'Contract', 'Freelance'].includes(employmentType);
        case 'income_in_range': {
            const min = Number(params.min ?? 0);
            const max = Number(params.max ?? Infinity);
            return income >= min && income <= max;
        }
        case 'income_above_x_times_rent': {
            const rent = Number(params.monthly_rent ?? 0);
            return income >= rent * 12 * 3;
        }
        default:
            return false;
    }
}

function evalMedical(
    fields: Record<string, unknown>,
    claimType: string,
    params: Record<string, unknown>
): boolean {
    const vaccinations = normalizeStringArray(fields.vaccinations);
    const allergies    = normalizeStringArray(fields.allergies);
    const conditions   = normalizeStringArray(fields.conditions);

    switch (claimType) {
        case 'vaccinated_for': {
            const disease = String(params.disease ?? '').toLowerCase();
            return vaccinations.some(v => v.toLowerCase().includes(disease));
        }
        case 'no_known_allergies':
            return allergies.length === 0;
        case 'allergy_free_of': {
            const allergen = String(params.allergen ?? '').toLowerCase();
            return !allergies.some(a => a.toLowerCase().includes(allergen));
        }
        case 'medically_fit':
            return conditions.length === 0;
        default:
            return false;
    }
}

function evalProperty(
    fields: Record<string, unknown>,
    claimType: string,
    params: Record<string, unknown>
): boolean {
    const value        = Number(fields.assessed_value ?? 0);
    const purchaseYear = Number(fields.purchase_year  ?? 0);

    switch (claimType) {
        case 'is_property_owner':
            return value > 0;
        case 'property_value_above': {
            const threshold = Number(params.threshold ?? 0);
            return value > threshold;
        }
        case 'purchased_before': {
            const year = Number(params.year ?? 9999);
            return purchaseYear <= year;
        }
        default:
            return false;
    }
}

function evalIdentity(
    fields: Record<string, unknown>,
    claimType: string,
    params: Record<string, unknown>
): boolean {
    const dob         = String(fields.date_of_birth ?? '');
    const nationality = String(fields.nationality   ?? '').toLowerCase();
    const ageYears    = dobToAgeYears(dob);

    switch (claimType) {
        case 'is_adult':
            return ageYears >= 18;
        case 'age_above': {
            const threshold = Number(params.threshold ?? 18);
            return ageYears >= threshold;
        }
        case 'nationality_is': {
            const country = String(params.country ?? '').toLowerCase();
            return country.length > 0 && nationality.includes(country);
        }
        default:
            return false;
    }
}

// ── Proof generation ──────────────────────────────────────────────────────────

export interface GenerateProofParams {
    /** Private: the plaintext document fields */
    fields:      Record<string, unknown>;
    /** Private: the salt used when computing the commitment */
    documentSalt: string; // base64
    /** Public: the document commitment (registered on Cascade during upload) */
    documentCommitment: string; // base64
    schemaType:  SchemaType;
    claimType:   string;
    claimParams: Record<string, unknown>;
    ownerAddress: string;
    /** Optional: proof lifespan in milliseconds. Null = never expires. */
    expiresInMs?: number | null;
}

/**
 * Generate a ZK proof for a specific claim about a document.
 *
 * Runs entirely on the user's device. The private `fields` and `documentSalt`
 * are never sent anywhere. Only the returned MidnightProof is shared.
 *
 * Proof construction (mirrors Groth16 workflow):
 *   1. Evaluate the claim (circuit execution)
 *   2. Compute witness hash:
 *      witnessHash = BLAKE2b(fields_json | claimType | claimParams_json | documentSalt)
 *   3. Derive simulated Groth16 points from witnessHash:
 *      π_A = BLAKE2b(witnessHash | "A"), π_B = (BLAKE2b(witnessHash | "Bx"), BLAKE2b(witnessHash | "By")), π_C = BLAKE2b(witnessHash | "C")
 *   4. Compute nullifier:
 *      nullifier = BLAKE2b(commitment_bytes | claimType_bytes | claimParams_json_bytes)
 *   5. Compute verification hash (public binding):
 *      vhash = BLAKE2b(π_A | π_C | satisfiesClaim_byte | nullifier_bytes | vk_bytes)
 */
export async function generateMidnightProof(
    p: GenerateProofParams
): Promise<MidnightProof> {
    const te = new TextEncoder();

    // ── 1. Evaluate the Compact circuit ─────────────────────────────────────
    const satisfiesClaim = evaluateClaim(p.schemaType, p.fields, p.claimType, p.claimParams);

    // ── 2. Compute witness hash (private) ────────────────────────────────────
    // The witness binds the proof to: specific fields + specific claim + document
    const fieldsJson      = JSON.stringify(p.fields, Object.keys(p.fields).sort());
    const claimParamsJson = JSON.stringify(p.claimParams, Object.keys(p.claimParams).sort());
    const saltBytes       = fromBase64(p.documentSalt);

    const witnessInput = concat(
        te.encode(fieldsJson),
        te.encode(p.claimType),
        te.encode(claimParamsJson),
        saltBytes
    );
    const witnessHash = blake2b256(witnessInput);

    // ── 3. Derive simulated Groth16 proof points ─────────────────────────────
    // In real Midnight: these are actual elliptic curve points on BLS12-377
    const piA  = toHex(blake2b256(concat(witnessHash, te.encode('ZK_GROTH16_PI_A'))));
    const piBx = toHex(blake2b256(concat(witnessHash, te.encode('ZK_GROTH16_PI_B_X'))));
    const piBy = toHex(blake2b256(concat(witnessHash, te.encode('ZK_GROTH16_PI_B_Y'))));
    const piC  = toHex(blake2b256(concat(witnessHash, te.encode('ZK_GROTH16_PI_C'))));

    const proof: Groth16Proof = { a: piA, b: [piBx, piBy], c: piC };

    // ── 4. Compute nullifier ──────────────────────────────────────────────────
    const commitmentBytes  = fromBase64(p.documentCommitment);
    const nullifierInput   = concat(
        commitmentBytes,
        te.encode(p.claimType),
        te.encode(claimParamsJson)
    );
    const nullifier = toBase64(blake2b256(nullifierInput));

    // ── 5. Look up circuit verification key ───────────────────────────────────
    const vkBytes = deriveCircuitVK(p.schemaType, p.claimType);
    const vk      = toBase64(vkBytes);

    // ── 6. Compute verification hash (public binding) ─────────────────────────
    // Maps: (proof points, verdict, nullifier, vk) → a single hash
    // Verifier recomputes this; the hash match proves structural integrity
    const satisfiesByte  = new Uint8Array([satisfiesClaim ? 1 : 0]);
    const nullifierBytes = fromBase64(nullifier);
    const piABytes       = fromBase64(toBase64(blake2b256str(piA)));
    const piCBytes       = fromBase64(toBase64(blake2b256str(piC)));

    const vhInput = concat(piABytes, piCBytes, satisfiesByte, nullifierBytes, vkBytes);
    const verificationHash = toBase64(blake2b256(vhInput));

    // ── 7. Simulate Midnight transaction submission ──────────────────────────
    // In production: actual Midnight tx with the proof bytes
    const txInput    = concat(fromBase64(nullifier), te.encode(p.ownerAddress), randomSalt());
    const midnightTxHash = toHex(blake2b256(txInput));

    // ── 8. Assemble proof bundle ──────────────────────────────────────────────
    const proofId = randomId();

    return {
        proofId,
        schemaType:         p.schemaType,
        contractId:         DEPLOYED_CONTRACTS[p.schemaType],
        claimType:          p.claimType,
        claimParams:        p.claimParams,
        claimDescription:   renderClaimDescription(p.schemaType, p.claimType, p.claimParams),
        satisfiesClaim,
        documentCommitment: p.documentCommitment,
        nullifier,
        proof,
        verificationHash,
        vk,
        ownerAddress:       p.ownerAddress,
        timestamp:          Date.now(),
        expiresAt:          p.expiresInMs != null ? Date.now() + p.expiresInMs : null,
        midnightTxHash,
        networkVersion:     MIDNIGHT_NETWORK_VERSION,
    };
}

// ── Proof verification ────────────────────────────────────────────────────────

/**
 * Verify a Midnight proof bundle.
 *
 * This runs on the verifier's device and requires NO access to the original document.
 * It checks structural integrity: that the proof points, verdict, and nullifier
 * are consistent with the verification hash.
 *
 * In production: this would be an on-chain pairing check on Midnight.
 */
export function verifyMidnightProof(proof: MidnightProof): VerificationResult {
    const te = new TextEncoder();

    try {
        // ── Expiry check ──────────────────────────────────────────────────────
        if (proof.expiresAt !== null && Date.now() > proof.expiresAt) {
            return makeInvalid(proof, 'Proof has expired.');
        }

        // ── Network version check ─────────────────────────────────────────────
        if (proof.networkVersion !== MIDNIGHT_NETWORK_VERSION) {
            return makeInvalid(proof, `Proof from unknown network: ${proof.networkVersion}`);
        }

        // ── Contract ID check ─────────────────────────────────────────────────
        const expectedContract = DEPLOYED_CONTRACTS[proof.schemaType];
        if (proof.contractId !== expectedContract) {
            return makeInvalid(proof, 'Contract ID does not match expected circuit.');
        }

        // ── VK check ─────────────────────────────────────────────────────────
        const expectedVkBytes = deriveCircuitVK(proof.schemaType, proof.claimType);
        const expectedVk      = toBase64(expectedVkBytes);
        if (proof.vk !== expectedVk) {
            return makeInvalid(proof, 'Verification key mismatch — possible circuit tampering.');
        }

        // ── Nullifier format check ────────────────────────────────────────────
        // Nullifier byte length must be 32 (256-bit BLAKE2b output)
        const nullifierBytes = fromBase64(proof.nullifier);
        if (nullifierBytes.length !== 32) {
            return makeInvalid(proof, 'Malformed nullifier.');
        }

        // ── Verification hash check ───────────────────────────────────────────
        // Re-derive the verification hash from proof components
        const satisfiesByte  = new Uint8Array([proof.satisfiesClaim ? 1 : 0]);
        const piABytes       = fromBase64(toBase64(blake2b256str(proof.proof.a)));
        const piCBytes       = fromBase64(toBase64(blake2b256str(proof.proof.c)));

        const vhInput       = concat(piABytes, piCBytes, satisfiesByte, nullifierBytes, expectedVkBytes);
        const expectedVH    = toBase64(blake2b256(vhInput));
        const claimParamsJson = JSON.stringify(proof.claimParams, Object.keys(proof.claimParams).sort());

        // Verify the nullifier is derived from commitment + claimType + claimParams
        const expectedNullifierInput = concat(
            fromBase64(proof.documentCommitment),
            te.encode(proof.claimType),
            te.encode(claimParamsJson)
        );
        const expectedNullifier = toBase64(blake2b256(expectedNullifierInput));

        if (proof.nullifier !== expectedNullifier) {
            return makeInvalid(proof, 'Nullifier does not match commitment/claim binding.');
        }

        if (proof.verificationHash !== expectedVH) {
            return makeInvalid(proof, 'Verification hash mismatch — proof integrity check failed.');
        }

        // ── All checks passed ─────────────────────────────────────────────────
        const verdict = proof.satisfiesClaim
            ? `✅ VERIFIED: ${proof.claimDescription}`
            : `❌ NOT MET: ${proof.claimDescription}`;

        return {
            valid:            true,
            satisfiesClaim:   proof.satisfiesClaim,
            claimDescription: proof.claimDescription,
            schemaType:       proof.schemaType,
            claimType:        proof.claimType,
            claimParams:      proof.claimParams,
            ownerAddress:     proof.ownerAddress,
            timestamp:        proof.timestamp,
            proofId:          proof.proofId,
            contractId:       proof.contractId,
            summary:          verdict,
        };
    } catch (err) {
        return makeInvalid(proof, `Verification error: ${String(err)}`);
    }
}

function makeInvalid(proof: MidnightProof, error: string): VerificationResult {
    return {
        valid:            false,
        satisfiesClaim:   false,
        claimDescription: proof.claimDescription ?? '',
        schemaType:       proof.schemaType,
        claimType:        proof.claimType,
        claimParams:      proof.claimParams ?? {},
        ownerAddress:     proof.ownerAddress ?? '',
        timestamp:        proof.timestamp    ?? 0,
        proofId:          proof.proofId      ?? '',
        contractId:       proof.contractId   ?? '',
        summary:          `❌ INVALID: ${error}`,
        error,
    };
}

// ── Proof serialization ───────────────────────────────────────────────────────

/**
 * Serialize a proof to a URL-safe base64 string for sharing.
 */
export function serializeProof(proof: MidnightProof): string {
    const json  = JSON.stringify(proof);
    const bytes = new TextEncoder().encode(json);
    let binary  = '';
    bytes.forEach(b => { binary += String.fromCharCode(b); });
    return btoa(binary)
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '');
}

/**
 * Deserialize a proof from a URL-safe base64 string.
 */
export function deserializeProof(encoded: string): MidnightProof {
    const b64 = encoded
        .replace(/-/g, '+')
        .replace(/_/g, '/');
    const padded = b64 + '==='.slice((b64.length + 3) % 4 === 0 ? 3 : (b64.length + 3) % 4);
    const binary = atob(padded);
    const bytes  = Uint8Array.from(binary, c => c.charCodeAt(0));
    const json   = new TextDecoder().decode(bytes);
    return JSON.parse(json) as MidnightProof;
}

/**
 * Build a shareable proof link (fragment-based, no server needed).
 */
export function buildProofLink(proof: MidnightProof): string {
    const encoded = serializeProof(proof);
    return `${window.location.origin}${window.location.pathname}#verify/${encoded}`;
}

/**
 * Parse a proof from the current URL fragment, if present.
 */
export function parseProofFromUrl(): MidnightProof | null {
    const hash = window.location.hash;
    if (!hash.startsWith('#verify/')) return null;
    try {
        return deserializeProof(hash.slice('#verify/'.length));
    } catch {
        return null;
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function normalizeStringArray(val: unknown): string[] {
    if (Array.isArray(val)) return val.map(String);
    if (typeof val === 'string') {
        return val.split(',').map(s => s.trim()).filter(Boolean);
    }
    return [];
}

function dobToAgeYears(dob: string): number {
    if (!dob) return 0;
    const birth = new Date(dob);
    if (isNaN(birth.getTime())) return 0;
    const now   = new Date();
    let age     = now.getFullYear() - birth.getFullYear();
    const m     = now.getMonth() - birth.getMonth();
    if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) age--;
    return age;
}
